### ISSUE TITLE
can't assemble binary on windows: too big

### ISSUE THREAD

**Issue by lkeegan** [lkeegan/dune-test-build#3]
https://ci.appveyor.com/project/lkeegan/dune-copasi-static/builds/30186680#L5094

```
table overflow at offset 10000387
C:\Users\appveyor\AppData\Local\Temp\1\ccqVw1Rh.s: Assembler messages:
C:\Users\appveyor\AppData\Local\Temp\1\ccqVw1Rh.s: Fatal error: can't close CMakeFiles/dune_copasi_md_lib.dir/dune_copasi_md.cc.obj: File too big
```
usual fix is to use `-O3`, but we're already doing this <https://stackoverflow.com/a/29479701/6465472>

maybe try separating the libs further, to only have a single model instantiation?

**Comment by SoilRos** [comment]
Fair enough. I will probably split libraries even more. That may resolve your problem but will increase compilation time. Will take a look at it next Monday.

**Comment by lkeegan** [comment]
temporary fix: <https://github.com/lkeegan/dune-copasi-static/commit/89aa167eb3954e1e4604ca3c7e5d954f0ef8d4da>
